owner: codechef-org
repo: status

sites:
  - name: CodeChef
    url: https://www.codechef.com
    icon: https://s3.amazonaws.com/codechef_shared/misc/favicon.ico
  - name: CodeChef Discuss
    url: https://discuss.codechef.com
    icon: https://s3.amazonaws.com/discourseproduction/optimized/1X/cb736284dfcba3606ca2751d7bafe7ac0be12b54_2_180x180.png
  - name: CodeChef Blog
    url: https://blog.codechef.com
    icon: https://blog.codechef.com/wp-content/themes/mediumish/images/favicon.ico
  - name: CodeChef Goodies
    url: https://goodies.codechef.com
    icon: https://s3.amazonaws.com/codechef-goodies/wp-content/uploads/2018/09/07183010/cropped-favicon-192x192.png
  - name: CodeChef Business
    url: https://business.codechef.com
    icon: https://s3.amazonaws.com/codechef_shared/misc/favicon.ico
  - name: CodeChef Campus
    url: https://campus.codechef.com
    icon: https://campus.codechef.com/images/favicon.ico
  - name: CodeChef API
    url: https://api.codechef.com/urls
    icon: https://s3.amazonaws.com/codechef_shared/misc/favicon.ico 
  - name: Broken Site
    url: https://thissitedoesnotexist.com    

status-website:
  cname: status.codechef.com
  logoUrl: https://www.codechef.com/sites/all/themes/abessive/logo.svg
  name: CodeChef | Status
  introTitle: "**CodeChef** - One of the world’s largest and popular global competitive programming platforms preferred by student & professional programmers."
  introMessage: This is a status page for all CodeChef sites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
